fix gpt
git-svn-id: https://svn.comics.unina.it/bismark/trunk@154 e00a4238-d597-4720-b6f7-de6324f10642

diff --git a/server/scripts/bdm b/server/scripts/bdm
--- a/server/scripts/bdm
+++ b/server/scripts/bdm
@@ -292,7 +292,7 @@ function start_tunnel()
 
 	if [ $2 ]; then
 		echo "Starting SSH tunnel to dev $1 on port $FWD_PORT (to $2)"
-		send_msg $1 fwd $FWD_PORT%$2 || { echo -e "\nDelivery to $1 failed"; return 2; }
+		send_msg $1 fwd $FWD_PORT:$2 || { echo -e "\nDelivery to $1 failed"; return 2; }
 	else
 		echo "Starting SSH tunnel to dev $1 on port $FWD_PORT"
 		send_msg $1 fwd $FWD_PORT || { echo -e "\nDelivery to $1 failed"; return 2; }
