OpenWrt_common basic scripts update
git-svn-id: https://svn.comics.unina.it/bismark/trunk@310 e00a4238-d597-4720-b6f7-de6324f10642

diff --git a/device/OpenWrt_common/scripts/action b/device/OpenWrt_common/scripts/action
--- a/device/OpenWrt_common/scripts/action
+++ b/device/OpenWrt_common/scripts/action
@@ -9,8 +9,8 @@
 # author: walter.dedonato@unina.it
 
 # Import configuration and functions
-. ~/conf/dev.conf
-. ~/scripts/functions
+. $BISMARK_DIR/etc/bismark.conf
+. $BISMARK_DIR/scripts/functions
 
 # Help screen
 [ $1 ] || { echo "$(basename $0) <command> [options]" ; exit ; }
@@ -36,10 +36,10 @@ pong)	# Server heartbeat
 		date -s @$ltime
 		hwclock -w
 	fi
-	echo $ltime > /tmp/server_last
+	echo $ltime > $BISMARK_DIR/var/server_last
 
 	# Store public IP 
-	echo $2 > /tmp/ip
+	echo $2 > $BISMARK_DIR/var/ip
 ;;
 update)	# Software update
 
@@ -47,103 +47,47 @@ update)	# Software update
 	[ $2 ] && [ $VERSION -eq $2 ] && { echo "Device up to date" | output $1 ; exit ; }
 
 	# Start svn update
-	svn update | output $1
+	svn update $BISMARK_DIR | output $1
 
 	# Apply changes
-	crontab ~/conf/crontab
+	crontab $BISMARK_DIR/etc/crontab
 
 	# Set restart flag
-	touch /tmp/restart
+	touch $BISMARK_DIR/var/restart
 ;;
 config)
 	# Modify parameters	
 	if [ "$2" ]; then 
-		if [ "$2" == "push" ]; then
-			push=1
-		else
-			# Copy current local.conf
-			cat local.conf > /tmp/local.conf
+		# Parse new configuration
+		IFS=$'&'
+		for param in $2; do
+			name=${param%=*}
+			value="${param#*=}"
 
-			# Parse new configuration
-			IFS=$'&'
-			for param in $2; do
-				name=${param%=*}
-				value="${param#*=}"
+			# Check generic parameter validity
+			grep -q "^$name=" $BISMARK_DIR/etc/{bismark,local}.conf || { echo -e "Invalid option $name\n" >&2; continue ; }
 
-				# Check generic parameter validity
-				grep -q "^$name=" conf/dev.conf local.conf || { echo -e "Invalid option $name\n" >&2; continue ; }
+			# Assign new value to parameter
+			eval "$name=\"$value\""
 
-				# Check specific parameters validity
-				case $name in
-				WIFI_CHANNEL) 
-					[ "$value" -ge 1 -a "$value" -le 11 ] || { echo -e "WIFI_CHANNEL must be an integer from 1 to 11" >&2; continue ; }
-				;;
-				WIFI_SSID) 
-					[ ${#value} -ge 1 -a ${#value} -le 32 ] || { echo -e "WIFI_SSID must be a string from 1 to 32 characters" >&2; continue ; }
-				;;
-				WIFI_SEC)
-					echo "$value" | grep -q '^WPA$\|^WPA2$\|^WEP$\|^NONE$' || { echo -e "WIFI_SEC must be one of NONE,WEP,WPA,WPA2" >&2; continue ; }
-				;;
-				esac
-
-				# Check WIFI parameters presence
-				[ ${name:0:4} == WIFI ] && push=1
-				
-				# Assign new value to parameter
-				eval "$name=\"$value\""
-
-				if [ "$value" ]; then
-					# Store parameter 
-					if grep -q "^$name=" /tmp/local.conf; then
-						# Substitute
-						mod_conf /tmp/local.conf $name "$value"
-					else
-						# Append
-						echo $name="$value" >> /tmp/local.conf
-					fi
-				elif grep -q "^$name=" /tmp/local.conf; then
-					# Remove parameter from local.conf
-					mod_conf /tmp/local.conf $name
+			if [ "$value" ]; then
+				# Store parameter 
+				if grep -q "^$name=" /tmp/local.conf; then
+					# Substitute
+					mod_conf /tmp/local.conf $name "$value"
+				else
+					# Append
+					echo $name="$value" >> /tmp/local.conf
 				fi
-			done
-
-			if [ $push ]; then
-				# Check wifi configuration consistency
-				case $WIFI_SEC in
-				WPA|WPA2)
-					[ ${#WIFI_PASS} -ge 8 -a ${#WIFI_PASS} -le 64 ] || { 
-						echo -e "When using WPA/WPA2, WIFI_PASS must be a string from 8 to 64 characters" >&2
-						error=1
-					}
-				;;
-				WEP) 
-					echo $WIFI_PASS | gawk '
-						{ 
-							len=length($0) 
-							if (len ~ /^5$|^13$|^16$/){ exit 0 }
-							if (len ~ /^10$|^26$|^32$/ && /^[0-9a-f]+$/){ exit 0 } 
-							exit 1 
-						}' || { 
-							echo -e "When using WEP, WIFI_PASS must be a string (5, 13, or 16 characters) or hexadecimal digits (10, 26, or 32 digits)" >&2
-							error=1
-						}
-				;;
-				esac
+			elif grep -q "^$name=" /tmp/local.conf; then
+				# Remove parameter from local.conf
+				mod_conf /tmp/local.conf $name
 			fi
-			[ $error ] && { push= ; rm /tmp/local.conf ; } || { mv /tmp/local.conf ~ ; cp ~/local.conf{,.bkp} ; }
-		fi
-	fi
-
-	# Push configuration
-	if [ $push ]; then
-		uci set wireless.wl0.channel=$WIFI_CHANNEL
-		uci set wireless.@wifi-iface[0].ssid=$WIFI_SSID
-		uci set wireless.@wifi-iface[0].key=$WIFI_PASS
-		uci commit wireless && wifi
+		done
 	fi
 
 	# Configuration output
-	set | awk -F'=' '(FNR==1){ f+=1 } /=/{ if (f == 1){a[$1]=1} else { if (a[$1] == 1) print $1 "=" $2} }' ~/conf/dev.conf - | output $1
+	set | awk -F'=' '(FNR==1){ f+=1 } /=/{ if (f == 1){a[$1]=1} else { if (a[$1] == 1) print $1 "=" $2} }' $BISMARK_DIR/etc/bismark.conf - | output $1
 ;;
 esac
 
