revised active measures (ditg disabled)
git-svn-id: https://svn.comics.unina.it/bismark/trunk@336 e00a4238-d597-4720-b6f7-de6324f10642

diff --git a/device/OpenWrt_common/scripts/bismark-dns b/device/OpenWrt_common/scripts/bismark-dns
--- a/device/OpenWrt_common/scripts/bismark-dns
+++ b/device/OpenWrt_common/scripts/bismark-dns
@@ -1,37 +1,40 @@
 #!/bin/ash
-# Bismark dns wrapper
-#
+# Bismark nslookup wrapper
+# 
 # author: walter.dedonato@unina.it
 
 # Load configuration files
 . /etc/bismark/bismark.conf
 . /usr/lib/bismark/functions.inc.sh
 
+# Settings
+DATA_DIR=/tmp/bismark/active/nslookup
+mkdir -p $DATA_DIR
+
 # Get IP and default DNS server
-get_ip
-[ -e /etc/resolv.conf ] && dds=$(awk '/^nameserver/{ print $2 ; exit }' /etc/resolv.conf)
+get_ip	# Returns $src
+[ -e /etc/resolv.conf ] && local_dns=$(awk '/^nameserver/{ print $2 ; exit }' /etc/resolv.conf)
+
 
 # Cycle DNS servers (default and OpenDNS)
-mkdir -p /tmp/host
-for s in "$dds" "8.8.8.8"; do
-
+for s in "$local_dns" "8.8.8.8"; do
 	# Cycle cache no-cache 
 	for m in NC C; do
 		# Cycle top 10 hosts list
 		fail=0
 		count=0
-		rm /tmp/host/delays
+                rm $DATA_DIR/delays
 
 		IFS=$'\n'
-		for h in $(cat ~/conf/hosts.list); do
-			~/bin/time -f %e --append -o /tmp/host/delays host $h $s >/dev/null || : $((fail++))
+		for h in $(cat /usr/lib/bismark/hosts.list); do
+                        time -f %e --append -o $DATA_DIR/delays nslookup $h $s >/dev/null || : $((fail++))
 			: $((count++))
 		done
 
 		# Output
 		[ $s ] || s="127.0.0.1"
-		grep '^[0-9]' /tmp/host/delays | mstats DNSDELAY$m HOST $src $s
-		awk 'BEGIN{ print ('$fail'/'$count') * 100 }' | mstats DNSFAIL$m HOST $src $s
+                grep '^[0-9]' $DATA_DIR/delays | bismark-mstats DNSDELAY$m HOST $src $s
+		awk 'BEGIN{ print ('$fail'/'$count') * 100 }' | bismark-mstats DNSFAIL$m HOST $src $s
 	done
 done
 
